name: PullRequest

on:
  pull_request:
    branches:
      - main

jobs:
  cicd:
    name: cicd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [lint, test-all, test-changed]
    steps:
      - name: check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install node in the runner
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      # Install and cache node modules
      - name: run yarn
        run: yarn

      - name: Run matrix command
        run: npm run ${{ matrix.command }}

      - name: Success ✅
        if: ${{success()}}
        run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{
            "context": "tests",
            "state": "success",
            "description": "Checks passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - id: Failure
        name: Failure 🚨
        if: ${{failure()}}
        run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{
            "context": "tests",
            "state": "failure",
            "description": "Checks failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
