name: PullRequest

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup-workflow.yml

  cicd:
    name: cicd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [tests-changed]
    steps:
      - name: Run matrix command
        needs: setup
        uses: ./.github/workflows/${{matrix.command}}-workflow.yml

      - name: Success ✅
        if: ${{success()}}
        run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{
            "context": "tests",
            "state": "success",
            "description": "Checks passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - id: Failure
        name: Failure 🚨
        if: ${{failure()}}
        run: |
          curl --request POST --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{
            "context": "tests",
            "state": "failure",
            "description": "Checks failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
