name: PullRequest

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      # Informational
      - id: GithubContext
        name: DumpGitHubcontext
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      # checkout repo for the particular commit SHA
      - id: CheckoutRepo
        name: CheckoutRepo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: GetDiffFiles
        name: GetDiffFiles
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            src/**/*.+(js|jsx|ts|tsx)
            !src/styles/**/*.js
            .storybook/**/*.+(js|jsx)
          FILES: |
            yarn.lock
            .eslintrc.json

      # Dump the diffed files for debugging purposes
      - id: DumpDiffedFiles
        name: DumpDiffedFiles
        if: env.GIT_DIFF_FILTERED
        run: echo ${{ env.GIT_DIFF_FILTERED }}

      - id: DumpMatchedFiles
        name: DumpMatchedFiles
        if: env.MATCHED_FILES
        run: echo ${{ env.MATCHED_FILES }}

      # Install node in the runner
      - id: InstallNode
        if: env.GIT_DIFF_FILTERED || env.MATCHED_FILES
        name: InstallNode
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      # Install and cache node modules
      - id: InstallNodeModules
        name: InstallNodeModules
        if: env.GIT_DIFF_FILTERED || env.MATCHED_FILES
        run: |
          yarn install --immutable
