name: PullRequest

on: [workflow_call]

jobs:
  tests-changed:
    name: tests-changed
    runs-on: ubuntu-latest
    steps:
      - id: RunAllTests
        name: RunAllTests
        if: env.GIT_DIFF_FILTERED || env.MATCHED_FILES
        run: |
          yarn test --onlyChanged --ci --silent --coverage --maxWorkers=50% | tee ./coverage.txt && exit ${PIPESTATUS[0]}

      - id: CommentCoverage
        name: CommentCoverage
        if: env.GIT_DIFF_FILTERED || env.MATCHED_FILES
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-path: ./coverage.txt
          report-only-changed-files: true
          hide-summary: true
          remove-links-to-files: true
          remove-links-to-lines: true
